version: '3.3'
services:
  backend:
    container_name: backend_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - bot/.env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: pgsql_container
    image: postgres:13.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - bot/.env
    ports:
      - 5432:5432
volumes:
    postgres_data: