# Generated by Django 4.1.3 on 2022-11-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='material',
        ),
    ]
