# Generated by Django 4.1.3 on 2022-12-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0002_remove_land_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='garage',
            field=models.CharField(default='Нет', max_length=200, verbose_name='Наличие гаража'),
        ),
        migrations.AddField(
            model_name='land',
            name='sauna',
            field=models.CharField(default='Нет', max_length=200, verbose_name='Наличие бани'),
        ),
    ]
