# Generated by Django 4.1.3 on 2022-12-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0004_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15, verbose_name='Подписчики')),
                ('agency_name', models.CharField(max_length=200, verbose_name='Агентство недвижимости')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
