# Generated by Django 4.1.3 on 2022-12-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0005_subscriptors_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15, verbose_name='id')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Подписчики',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.AlterModelOptions(
            name='subscriptors',
            options={'verbose_name': 'Подписчики', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
