# Generated by Django 4.1.3 on 2022-12-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0006_individuals_alter_subscriptors_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individuals',
            options={'verbose_name': 'Частный риелтор', 'verbose_name_plural': 'Частные риелторы'},
        ),
    ]
