# Generated by Django 4.1.3 on 2022-12-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0008_apartment_photo_id_house_photo_id_land_photo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='photo_id',
        ),
        migrations.RemoveField(
            model_name='house',
            name='photo_id',
        ),
        migrations.RemoveField(
            model_name='land',
            name='photo_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo_id',
        ),
        migrations.RemoveField(
            model_name='townhouse',
            name='photo_id',
        ),
        migrations.AddField(
            model_name='apartment',
            name='photo_1_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи1'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='photo_2_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи2'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='photo_3_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи3'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='photo_4_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи4'),
        ),
        migrations.AddField(
            model_name='house',
            name='photo_1_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи1'),
        ),
        migrations.AddField(
            model_name='house',
            name='photo_2_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи2'),
        ),
        migrations.AddField(
            model_name='house',
            name='photo_3_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи3'),
        ),
        migrations.AddField(
            model_name='house',
            name='photo_4_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи4'),
        ),
        migrations.AddField(
            model_name='land',
            name='photo_1_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи1'),
        ),
        migrations.AddField(
            model_name='land',
            name='photo_2_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи2'),
        ),
        migrations.AddField(
            model_name='land',
            name='photo_3_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи3'),
        ),
        migrations.AddField(
            model_name='land',
            name='photo_4_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи4'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo_1_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи1'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo_2_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи2'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo_3_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи3'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo_4_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи4'),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='photo_1_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи1'),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='photo_2_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи2'),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='photo_3_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи3'),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='photo_4_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фотографи4'),
        ),
    ]
