# Generated by Django 4.1.3 on 2022-12-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0009_remove_apartment_photo_id_remove_house_photo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='photo_1_id',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='photo_2_id',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='photo_3_id',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='photo_4_id',
        ),
        migrations.RemoveField(
            model_name='house',
            name='photo_1_id',
        ),
        migrations.RemoveField(
            model_name='house',
            name='photo_2_id',
        ),
        migrations.RemoveField(
            model_name='house',
            name='photo_3_id',
        ),
        migrations.RemoveField(
            model_name='house',
            name='photo_4_id',
        ),
        migrations.RemoveField(
            model_name='land',
            name='photo_1_id',
        ),
        migrations.RemoveField(
            model_name='land',
            name='photo_2_id',
        ),
        migrations.RemoveField(
            model_name='land',
            name='photo_3_id',
        ),
        migrations.RemoveField(
            model_name='land',
            name='photo_4_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo_1_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo_2_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo_3_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo_4_id',
        ),
        migrations.RemoveField(
            model_name='townhouse',
            name='photo_1_id',
        ),
        migrations.RemoveField(
            model_name='townhouse',
            name='photo_2_id',
        ),
        migrations.RemoveField(
            model_name='townhouse',
            name='photo_3_id',
        ),
        migrations.RemoveField(
            model_name='townhouse',
            name='photo_4_id',
        ),
        migrations.AddField(
            model_name='apartment',
            name='media_group_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID альбома'),
        ),
        migrations.AddField(
            model_name='house',
            name='media_group_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID альбома'),
        ),
        migrations.AddField(
            model_name='land',
            name='media_group_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID альбома'),
        ),
        migrations.AddField(
            model_name='room',
            name='media_group_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID альбома'),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='media_group_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID альбома'),
        ),
    ]
