# Generated by Django 4.1.3 on 2022-12-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0010_remove_apartment_photo_1_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='media_group_id',
        ),
        migrations.RemoveField(
            model_name='house',
            name='media_group_id',
        ),
        migrations.RemoveField(
            model_name='land',
            name='media_group_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='media_group_id',
        ),
        migrations.RemoveField(
            model_name='townhouse',
            name='media_group_id',
        ),
        migrations.AddField(
            model_name='apartment',
            name='photo_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фото'),
        ),
        migrations.AddField(
            model_name='house',
            name='photo_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фото'),
        ),
        migrations.AddField(
            model_name='land',
            name='photo_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фото'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фото'),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='photo_id',
            field=models.CharField(default='AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ', max_length=500, verbose_name='ID фото'),
        ),
    ]
