# Generated by Django 4.1.3 on 2022-12-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0011_remove_apartment_media_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='photo_id',
            field=models.CharField(default='[AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ]', max_length=500, verbose_name='ID фото'),
        ),
        migrations.AlterField(
            model_name='house',
            name='photo_id',
            field=models.CharField(default='[AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ]', max_length=500, verbose_name='ID фото'),
        ),
        migrations.AlterField(
            model_name='land',
            name='photo_id',
            field=models.CharField(default='[AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ]', max_length=500, verbose_name='ID фото'),
        ),
        migrations.AlterField(
            model_name='room',
            name='photo_id',
            field=models.CharField(default='[AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ]', max_length=500, verbose_name='ID фото'),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='photo_id',
            field=models.CharField(default='[AgACAgIAAxkBAAIgfmOa2LfSqhWFbSd3cezejErLCUPQAAIWvzEb1EDYSPq4knc5HwhjAQADAgADeQADLAQ]', max_length=500, verbose_name='ID фото'),
        ),
    ]
