# Generated by Django 4.1.3 on 2022-12-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0018_alter_house_photo_id_alter_land_photo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='площадь квартиры'),
        ),
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Площадь дома'),
        ),
        migrations.AlterField(
            model_name='house',
            name='area_of_land',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Площадь участка'),
        ),
        migrations.AlterField(
            model_name='land',
            name='area_of_land',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Площадь участка'),
        ),
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='площадь комнаты'),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='area',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Площадь дома'),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='area_of_land',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Площадь участка'),
        ),
    ]
