# Generated by Django 4.1.3 on 2022-12-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0020_alter_apartment_price_alter_house_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='code_word',
            field=models.CharField(default='слово', max_length=200, verbose_name='кодовое слово'),
        ),
        migrations.AddField(
            model_name='house',
            name='code_word',
            field=models.CharField(default='слово', max_length=200, verbose_name='кодовое слово'),
        ),
        migrations.AddField(
            model_name='land',
            name='code_word',
            field=models.CharField(default='слово', max_length=200, verbose_name='кодовое слово'),
        ),
        migrations.AddField(
            model_name='room',
            name='code_word',
            field=models.CharField(default='слово', max_length=200, verbose_name='кодовое слово'),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='code_word',
            field=models.CharField(default='слово', max_length=200, verbose_name='кодовое слово'),
        ),
    ]
