# Generated by Django 4.1.3 on 2022-12-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0021_apartment_code_word_house_code_word_land_code_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='house',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='land',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='room',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='townhouse',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='individuals',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='id'),
        ),
    ]
