# Generated by Django 4.1.3 on 2022-12-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0022_apartment_user_id_house_user_id_land_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='user_id',
            field=models.BigIntegerField(default=1, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='house',
            name='user_id',
            field=models.BigIntegerField(default=1, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='individuals',
            name='user_id',
            field=models.BigIntegerField(default=1, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='land',
            name='user_id',
            field=models.BigIntegerField(default=1, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_id',
            field=models.BigIntegerField(default=1, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='user_id',
            field=models.BigIntegerField(default=1, verbose_name='id'),
        ),
    ]
