# Generated by Django 4.1.3 on 2022-12-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0024_buyer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_name',
            field=models.CharField(default='Не спросил', max_length=200, verbose_name='Имя покупателя'),
        ),
    ]
