# Generated by Django 4.1.3 on 2022-12-27 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0025_alter_buyer_options_buyer_buyer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата внесения'),
            preserve_default=False,
        ),
    ]
