# Generated by Django 4.1.3 on 2023-01-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0026_buyer_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='initial_payment',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='last_floor',
        ),
    ]
