# Generated by Django 4.1.3 on 2023-01-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0027_remove_buyer_initial_payment_remove_buyer_last_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='room_quantity',
        ),
    ]
